.TH LIGHTYENABLEMOD 1 2006-01-11
.SH NAME
lighty-enable-mod, lighty-disable-mod \- enable or disable configuration in lighttpd server
.SH SYNOPSIS
lighty-enable-mod [module]
lighty-disable-mod [module]
.SH DESCRIPTION
This manual page documents briefly the lighty-enable-mod and
lighty-disable-mod commands.

lighty-enable-mod and lighty-disable-mod are programs that enable
(and respectively disable) the specified configuration file within
lighttpd configuration.
.SH SEE ALSO
lighttpd(1)
.SH AUTHOR
eloy@debian.org
